package istic.taa.wkapp.controller;

import istic.taa.wkapp.repository.ActivityRepository;
import istic.taa.wkapp.model.Activity;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/activity")
public class ActivityController {
    @Autowired // This means to get the bean called activityRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ActivityRepository activityRepository;

    /**
     * GET /activity  --> Get the list of all activities from the database.
     */
    @CrossOrigin(origins = "http://localhost:4200")
    @GetMapping(value = "/all")
    public Iterable<Activity> getAllActivities() {
        return activityRepository.findAll();
    }


}
